sonar.projectKey=DangTH27_example-voting-app
sonar.organization=dangth27

# Tên project hiển thị trên SonarCloud
sonar.projectName=example-voting-app
sonar.projectVersion=1.0

# Đường dẫn tới thư mục source code cần quét (bỏ qua k8s-specifications, seed-data, etc.)
sonar.sources=vote,result,worker

# Encoding
sonar.sourceEncoding=UTF-8
